//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriOdev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Subes = new HashSet<Sube>();
        }
    
        public int MusteriNo { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string MusteriTcNo { get; set; }
        public string MusteriMail { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriAdres { get; set; }
        public Nullable<int> AracNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sube> Subes { get; set; }
    }
}
