//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriOdev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Subes = new HashSet<Sube>();
        }
    
        public int PersonelNo { get; set; }
        public string PersonelAdSoyad { get; set; }
        public Nullable<int> PersonelYas { get; set; }
        public string PersonelTcNo { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelAdres { get; set; }
        public Nullable<int> SubeNo { get; set; }
    
        public virtual Sube Sube { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sube> Subes { get; set; }
    }
}
