USE [master]
GO
/****** Object:  Database [Pastane]    Script Date: 15.04.2022 16:24:49 ******/
CREATE DATABASE [Pastane]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pastane', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pastane.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pastane_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pastane_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Pastane] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pastane].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Pastane] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Pastane] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Pastane] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Pastane] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Pastane] SET ARITHABORT OFF 
GO
ALTER DATABASE [Pastane] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Pastane] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Pastane] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Pastane] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Pastane] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Pastane] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Pastane] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Pastane] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Pastane] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Pastane] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Pastane] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Pastane] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Pastane] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Pastane] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Pastane] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Pastane] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Pastane] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Pastane] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Pastane] SET  MULTI_USER 
GO
ALTER DATABASE [Pastane] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Pastane] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Pastane] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Pastane] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Pastane] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Pastane] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Pastane] SET QUERY_STORE = OFF
GO
USE [Pastane]
GO
/****** Object:  Table [dbo].[KullaniciGiris]    Script Date: 15.04.2022 16:24:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KullaniciGiris](
	[KullaniciNo] [int] IDENTITY(1,1) NOT NULL,
	[KullaniciAd] [varchar](50) NULL,
	[KullaniciSifre] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[Telefon] [char](20) NULL,
 CONSTRAINT [PK_KullaniciGiris] PRIMARY KEY CLUSTERED 
(
	[KullaniciNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Müsteriler]    Script Date: 15.04.2022 16:24:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Müsteriler](
	[MusteriNo] [int] IDENTITY(1,1) NOT NULL,
	[MusteriAdSoyad] [varchar](50) NULL,
	[MusteriTelefon] [char](20) NULL,
	[SiparisNo] [int] NULL,
 CONSTRAINT [PK_Müsteriler] PRIMARY KEY CLUSTERED 
(
	[MusteriNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Satýcý]    Script Date: 15.04.2022 16:24:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Satýcý](
	[SaticiNo] [int] IDENTITY(1,1) NOT NULL,
	[SaticiAdSoyad] [varchar](50) NULL,
	[SaticiAdres] [varchar](max) NULL,
	[SaticiÝl] [varchar](50) NULL,
	[SaticiÝlce] [varchar](50) NULL,
 CONSTRAINT [PK_Satýcý] PRIMARY KEY CLUSTERED 
(
	[SaticiNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sipariþ]    Script Date: 15.04.2022 16:24:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sipariþ](
	[SiparisNo] [int] IDENTITY(1,1) NOT NULL,
	[SiparisAdi] [varchar](50) NULL,
	[SiparisAdres] [varchar](max) NULL,
	[SiparisAdet] [int] NULL,
	[SiparisFiyat] [money] NULL,
	[UrunNo] [int] NULL,
	[Tutar] [money] NULL,
 CONSTRAINT [PK_Sipariþ] PRIMARY KEY CLUSTERED 
(
	[SiparisNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Urunler]    Script Date: 15.04.2022 16:24:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Urunler](
	[UrunNo] [int] IDENTITY(1,1) NOT NULL,
	[UrunAdi] [varchar](50) NULL,
	[UrunFiyat] [money] NULL,
	[KullanimTarihi] [varchar](50) NULL,
	[UretimTarihi] [varchar](50) NULL,
	[SaticiNo] [int] NULL,
 CONSTRAINT [PK_Urunler] PRIMARY KEY CLUSTERED 
(
	[UrunNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Müsteriler]  WITH CHECK ADD  CONSTRAINT [FK_Müsteriler_Sipariþ] FOREIGN KEY([SiparisNo])
REFERENCES [dbo].[Sipariþ] ([SiparisNo])
GO
ALTER TABLE [dbo].[Müsteriler] CHECK CONSTRAINT [FK_Müsteriler_Sipariþ]
GO
ALTER TABLE [dbo].[Sipariþ]  WITH CHECK ADD  CONSTRAINT [FK_Sipariþ_Urunler] FOREIGN KEY([UrunNo])
REFERENCES [dbo].[Urunler] ([UrunNo])
GO
ALTER TABLE [dbo].[Sipariþ] CHECK CONSTRAINT [FK_Sipariþ_Urunler]
GO
ALTER TABLE [dbo].[Urunler]  WITH CHECK ADD  CONSTRAINT [FK_Urunler_Satýcý] FOREIGN KEY([SaticiNo])
REFERENCES [dbo].[Satýcý] ([SaticiNo])
GO
ALTER TABLE [dbo].[Urunler] CHECK CONSTRAINT [FK_Urunler_Satýcý]
GO
USE [master]
GO
ALTER DATABASE [Pastane] SET  READ_WRITE 
GO
