//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2204022_EFproc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OkulEntities : DbContext
    {
        public OkulEntities()
            : base("name=OkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ogrenciler> Ogrencilers { get; set; }
    
        public virtual int OAdd(string adsoyad, string tcNo, string telefon, string mail, string adres)
        {
            var adsoyadParameter = adsoyad != null ?
                new ObjectParameter("Adsoyad", adsoyad) :
                new ObjectParameter("Adsoyad", typeof(string));
    
            var tcNoParameter = tcNo != null ?
                new ObjectParameter("TcNo", tcNo) :
                new ObjectParameter("TcNo", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OAdd", adsoyadParameter, tcNoParameter, telefonParameter, mailParameter, adresParameter);
        }
    
        public virtual ObjectResult<OG_Result> OG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OG_Result>("OG");
        }
    
        public virtual int OSL(Nullable<int> ogrenciNo)
        {
            var ogrenciNoParameter = ogrenciNo.HasValue ?
                new ObjectParameter("OgrenciNo", ogrenciNo) :
                new ObjectParameter("OgrenciNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OSL", ogrenciNoParameter);
        }
    
        public virtual int OY(Nullable<int> ogrenciNo, string adsoyad, string tcNo, string telefon, string mail, string adres)
        {
            var ogrenciNoParameter = ogrenciNo.HasValue ?
                new ObjectParameter("OgrenciNo", ogrenciNo) :
                new ObjectParameter("OgrenciNo", typeof(int));
    
            var adsoyadParameter = adsoyad != null ?
                new ObjectParameter("Adsoyad", adsoyad) :
                new ObjectParameter("Adsoyad", typeof(string));
    
            var tcNoParameter = tcNo != null ?
                new ObjectParameter("TcNo", tcNo) :
                new ObjectParameter("TcNo", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OY", ogrenciNoParameter, adsoyadParameter, tcNoParameter, telefonParameter, mailParameter, adresParameter);
        }
    }
}
