//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25042022_İefprocServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hizmetler()
        {
            this.HizmetOzelliklers = new HashSet<HizmetOzellikler>();
            this.Musterilers = new HashSet<Musteriler>();
        }
    
        public int HizmetNo { get; set; }
        public string HizmetAdi { get; set; }
        public string HizmetTanimi { get; set; }
        public Nullable<decimal> HizmetFiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HizmetOzellikler> HizmetOzelliklers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteriler> Musterilers { get; set; }
    }
}
