//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25042022_İefprocServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class HizmetOzellikler
    {
        public int HizmetOzellikNo { get; set; }
        public Nullable<int> HizmetOzellikHizmetNo { get; set; }
        public string HizmetAciklama { get; set; }
        public string HizmetOzellikEkstra { get; set; }
    
        public virtual Hizmetler Hizmetler { get; set; }
    }
}
