//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25042022_İefprocServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisNo { get; set; }
        public string SiparisAdi { get; set; }
        public Nullable<int> SiparisMusteriNo { get; set; }
        public string SiparisAdres { get; set; }
        public string SiparisAciklama { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
