//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20042022_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme
    {
        public int MalzemeId { get; set; }
        public string MalzemeAdi { get; set; }
        public int Adet { get; set; }
        public decimal Fiyat { get; set; }
        public string DepoAdi { get; set; }
    }
}
