//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp118042022_Entity_ilk_örnek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hocalar
    {
        public int HocaNo { get; set; }
        public string Adsoyad { get; set; }
        public string Brans { get; set; }
        public string Unvan { get; set; }
    }
}
