//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp118042022_Entity_ilk_örnek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int OgrenciNo { get; set; }
        public string Adsoyad { get; set; }
        public string TcNo { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
    }
}
