//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20042022Nordwınd_Sıralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biten_Urunler_Listesi
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
    }
}
